### ISSUE TITLE
Introduce yourself

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall20#1]
Hi everyone - 

I thought I'd kick off a post where everyone can reply with an introduction to themselves so we can get to know each other. 

**Tell us what brought you to this course and any other details you care to share.**

A little bit about myself - I'm a web programmer and educator, living in Arlington, MA.

In addition to this course, I also teach [DGMD E-28](https://hesweb.dev/e28) and [CSCI E-15](https://hesweb.dev/e15). I've also worked with students completing their capstones in the DGMD program.

In the past, I've taught at Wellesley, UPenn, and UMiami. When working in industry I was the head developer for an online e-commerce store. 

More about my background here: [susanbuck.net](https://susanbuck.net)

All in all, I love creating things with code and teaching others how to do the same.

Looking forward to getting to know you all!

**Comment by CrimsonSIS** [comment]
Greeting Comrades!

My name is **Jerald Dana Cole** (formally), not to be confused with the other Jerald Cole on campus (which is why I include my middle name).

Call me **Jerry** (informally).

I'm a married--non-smoking--caucasian--post-career--culturally-Jewish--male, rabid kayaker, SCUBA diver, over 60 and balding. My wife states that you wouldn't notice the latter at a gallup.

We love traveling to _scenic_ and _historic_ places. 

I've worked as a professor of computer science and educational technology for over 40 years AND as a software engineer for Warner Brothers, viaMax, PerkinElmer, Schlumberger-Doll and the New York City Board of Education, among others.

I'm versed in back-end server administration and enterprise level network management (the boring stuff--as it were) but **NOT** great at front-end aspects of web design--which is why I'm enrolled in _this_ class and the HES DGMD program. I've watched some of Professor Buck's terrific videos and heard & read scuttlebutt that she is a great teacher. These also induced me to take a shot at the class.

My pedigree includes Columbia, Harvard and Rensselaer. 

I'm a trustee at two not-for-profits: https://ctoxfordhouse.org and http://communitysolar.biz.

My capstone project, _CrimsonSIS,_ will utilize Django and PhP. I know bupkis about PhP, other than some rudimentary SSIs  in the past. 

Feel free to give me a jingle. I'm sequestered at home with my wife, cats (Uncle Fang and Prince Harry) and grumpy 83 year old father-in-law (non-rent paying tenant with an open-ended lease) due to the pandemic. I'd value any form of  coursework dialectic and could use the socialization.

My virtual coordinates are

Cell/Text/FaceTime (203) 982-0677
jerald_cole@alumni.harvard.edu

https://www.linkedin.com/in/jeralddanacole
https://www.facebook.com/jerald.d.cole
http://deltaphinureview.com

Best,

:-)

**Comment by tatthung** [comment]
Hi Classmates and Susan,

My name is Tatt, or Tee. 

I am a Malaysian, currently working in the HSBC bank in Hong Kong as a digital project manager. One of our upcoming important project is related to building a talent-acquisition website, which I believe the end of this course could greatly help me out building the system. Coming from Psychology background, I have minimal experience with programming. I have recently completed the Fundamental Web Development, and in love with programming already. I think its time for me to move forward to understand and learn more about the server-side programming. Hope to e-meet up with you all soon!

Best Regards,
Tatt

**Comment by CrimsonSIS** [comment]
Hi Tee:

Jerry Cole here! I posted my intro yesterday. Will check the forum as
people engage.

See you in "class."

Best,

:-)

**Comment by pllealfunes** [comment]
Hi Everyone, 

I'm Paula, and I am working towards the HES Web Technologies Certificate. I am intimidated by Back End Development, but I do believe that knowing at least something about it can be very beneficial. I do not come from a technical background, but I do hope to become a Front End Web Developer in the future.

I wish everyone good luck this semester. Thanks! =)

**Comment by pranjal-joshi97** [comment]
Hi All, 
Hope you're doing well! 

I'm Pranjal and I'm working towards my Undergrad Coding Certificate from Harvard Extension! I'm from India and Turkey, but came to Boston for my undergrad. 

I graduated last year with a B.S. in Business Administration from Babson College with concentrations in Strategic and I.T. Management. I have done web designing (HTML, CSS, JavaScript, Bootstrap, etc.) but wanted to expand my knowledge to server side programming. I don't have too much experience with other languages such as PHP or Python (I consider myself a beginner) so I thought this certificate would help me. 

I'm a fan of digital design, so using and learning new Adobe apps, and exploring UI/UX design to learn about digital product design. I aspire to go into the management consulting industry which I feel will allow me to blend my business and technical backgrounds (once I get this certificate haha). 

I'm looking forward to working and chatting with you in the forums :) 

Best, 
Pranjal

**Comment by maqboolk** [comment]
hi All,
My name is Maqbool and I am excited about this class. I have never worked with PHP before and want to learn more about it. 

Good luck all

**Comment by allanmglass12** [comment]
Hello all,

I'm excited to dive into the world of PHP! :) While I have experience w/ HTML, CSS, & Classic ASP ... PHP is a new experience for me and I'm eager to learn more about the programming language (and comparing/contrasting it to VBScript).

Currently, I'm teaching full time at [Endicott College](http://www.endicott.edu/) in Beverly, MA and I live in Salem, MA with my wife Lori and son Isaac.

Looking forward to a good course ...

Allan

**Comment by alysonann** [comment]
Hello,

My name is Alyson Lynch, and I currently am a staff member in the Department of the Classics at Harvard. I just finished the Front-End Web Development Certificate, and am working towards a degree in the Digital Media Design program. I live in Somerville, MA and am thankfully WFH with my dog Rudy! I'm excited to building on some intro programming experience and solidify my skills with this class.
![image](https://user-images.githubusercontent.com/31620333/92418219-6008bc00-f134-11ea-8855-697fd2f031d3.png)

Alyson

**Comment by kristysunnyd** [comment]
Hi everyone! 

I'm Kristy Sun, and I am definitely a nerd for technology as well as an avid daydreamer. I currently live in the skyscraper-filled city of Hong Kong. It is nice to meet everyone. 

I am taking this course because I've never used PHP before but have always wanted to learn how to use it, so this is very exciting for me. I have had a little experience with frontend web development and design, with HTML, CSS and some Javascript. 

Looking forward to learning lots in this course! :) Thanks!
Kristy

**Comment by trnason** [comment]
Hi Everyone!

My name is Tommy Nason and I live in Oklahoma City. I am taking this class as I pursue a masters in Digital Media Design. I have little to no prior programming experience so a little scared taking this class. 

I am a system analyst at Love's Travel Stops and I have heard them use words such as apache and PHP so thought this would be a good class to get some basics down. Looking forward to the semester!

**Comment by britney-sandau** [comment]
Greetings and salutations!

My name is Britney and I am looking forward to this class. I am originally from Idaho and I recently moved to Foxboro, MA about a year ago to complete my on-campus requirements but I love Massachusetts so much I may not want to move back. It is so beautiful here and I love exploring the historical sites. Now I just have to convince my spouse.

I am a newbie when it comes to website programming and design but I am hoping that I can become a Jedi Master one day. My interest in creating websites was sparked from a previous class in HTML and CSS and I would love to learn more on how to create a spectacular website. 

Looking forward to a great semester with you all!

Britney

**Comment by kmmoua** [comment]
Hi, everyone!  I'm Kao.

I am a career Soldier and a combat veteran of both Iraq and Afghanistan.  After 22 years of service, I am just about ready to take the boots off.  As I prepare for a full-time civilian career, I am pursuing the Programming Certificate at HES to build a solid foundation for the MIS Masters program.  DGMD E-2 is, of course, a part of the Programming Certificate.

Presently, I am stationed at Hanscom Air Force Base in Bedford, MA just a few minutes from the Harvard campus where I work at the Directorate of Information Management (DOIM) as a system administrator.  My team manages our part of the Department of Defense Information Network (DoDIN) supporting a user base of well over 10,000 service members and civilian employees.  I have approximately 10 years of experience in IT, but very little with programming.  I believe this educational path will be a great cornerstone of that foundation I'm building.

The other half of my military career was in military healthcare as a Combat Medic.  After nearly two decades of war and multiple combat deployments, I am honored to have played a small part in saving lives and lending comfort to unfortunate victims of warfare regardless of uniform or flag.

With that said, I'm very excited to start this new chapter of life.

**Comment by mborjon** [comment]
Hello all,

I work in Marketing in the Silicon Valley.  I have always said I was going to learn how to program, but have put it off for years.  This is my first official class.  I am very excited to focus on learning over the next few months with you all.

I am also interested in pursuing a certificate or maybe even the Digital Media Design Master's Degree.  

I am originally from Southern California.  I have been in the Bay Area of California for many years now and love the community, outdoors activities and the history.  

When I'm not working or studying, I enjoy spending time with my husband and 10 year old daughter.

Take care all!
-Melinda

**Comment by scoutperry** [comment]
Hello everyone!

My name is Scout, and I'm taking this as part of my pursuit of masters degree in Digital Media Design. I have taken courses In HTML, CSS, and Javascript, already and I am very excited to learn PHP. I am particularly interested in how these languages can work with PHP to enable communication between the website and the server. 

Usually I work at the security department of the Harvard Art Museums, but the museum is still closed to most of the community due to Covid-19. So instead I'm working as an AV contractor at MIT to help support their hybrid/flexible in person/online classes. 

I'm so excited to meet you all and learn PHP!

Best,
Scout

**Comment by chuckac** [comment]
Hey Folks, 

Chuck here and taking this course to help improved and keeps some of my skills relevant.  In *real life* I work with startups and entrepreneurs on the process of venture creation.  I'm filling out courses to complete the programming certificate, so that's the ultimate goal.  It's my first time taking a course at the extension school, and I'm very much looking forward to it.  I'm based out of South Boston, so when things improve, I'm open to socially responsible meetups!

Looking forward to the semester!

**Comment by rlange2176** [comment]
Hi all,

My name is Becca, and I live in the Boston area. I work at Harvard (in marketing at the Business School) and am taking this course as part of the Digital Media Design program at the Extension School. I'm pretty familiar with HTML and CSS but am new to programming. Hoping this course will be a good introduction!

Looking forward to getting to know everyone this semester!

Best,
Becca

**Comment by emmyzon** [comment]
Hello hello! 

My name is Emily, I live in Somerville and work at Harvard in the FAS Career Services Office. Last May I earned a certificate from HES in Front-End Web Development, and have recently decided to bite the bullet and pursue a Master's in Digital Media Design. Scary and exciting at the same time! Ultimately I'd love to end up in the Ed Tech industry. 

I have some experience with HTML/CSS and some JavaScript, but would still consider myself new-ish to programming. I am looking forward to practicing "thinking like a programmer" in this course this semester!


Warmly,
Emily

**Comment by miriamkifledev** [comment]
Hey everyone,

My name is Sara. I'm taking this class to learn about web development using PHP. While I am a novice in this space, I hope to learn as much as possible. I also look forward to getting to know everyone and hope that this will be a fruitful semester for us all. 

Cheers,
Sara

**Comment by susanBuck** [comment]
Thanks everyone for taking time to introduce yourselves! Enjoyed reading about your backgrounds and what brought you here.
