### ISSUE TITLE
Change permission for SQL for e2

### ISSUE THREAD

**Issue by mborjon** [susanBuck/e2-fall20#107]
Hello @susanBuck, 

I am trying to create a new database on production for p3.  It appears I do not have the privileges to do so for e2.  How can I change that?

Thanks,
-Melinda

**screen grab of terminal denying access**
<img width="864" alt="Screen Shot 2020-12-07 at 5 50 41 PM" src="https://user-images.githubusercontent.com/38201146/101428118-f627bc00-38b4-11eb-8cc6-50ebd023948f.png">

**.env file**
<img width="925" alt="Screen Shot 2020-12-07 at 5 51 03 PM" src="https://user-images.githubusercontent.com/38201146/101428101-ef994480-38b4-11eb-8dfe-c93247ec417d.png">

**Comment by susanBuck** [comment]
One of two things might be happening:

1. The password you're entering for `e2` is incorrect. 
2. The MySQL `e2` user does not exist (I did a test trying to connect to MySQL under a username that does not exist, and it will prompt for a password instead of telling you the user does not exist).

If the password is incorrect, you can connect to MySQL under the _root_ user and update the _e2_ user's password to something new.

[The instructions for finding your _root_ MySQL password are here...](https://hesweb.dev/e2/notes/php/db-production#find-your-default-mysql-password)

Once you have that password, connect as `root` with this command:

```
mysql -u root -p
```
This will prompt you for your _root_ password; enter the password you got in the previous step.

Assuming this gets you to the mysql prompt (`mysql> `), you can update your _e2_ password with this command:

```
ALTER USER 'e2'@'localhost' IDENTIFIED BY 'yourNewPasswordHere';
```

If for some reason the `e2` user does not exist, this command will return an error like this:

```
mysql> ALTER USER 'e2222'@'localhost' IDENTIFIED BY 'yourNewPasswordHere';
ERROR 1396 (HY000): Operation ALTER USER failed for 'e2222'@'localhost'
```

If that's the case, you can create the _e2_ user while logged in as the _root_ user following these steps:
https://hesweb.dev/e2/notes/php/db-production#create-a-new-mysql-user

**Comment by mborjon** [comment]
Thanks!
