### ISSUE TITLE
403 Forbidden page on Production

### ISSUE THREAD

**Issue by marroquin7** [susanBuck/e2-fall20#114]
Hello,
I have completed my project 3, but after I deployed it to the server I am getting a 403 Forbidden error when I visit my site HTTP://e2p3.cmarroquin.me
I restarted the Apache server, checked that the virtual host is set up correctly, but nothing seems to be working. Attached are images for reference. I also try accessing the link from a different device, but I got the same issue. 

![403](https://user-images.githubusercontent.com/60824426/101718658-afca8c80-3a6f-11eb-96af-e668ef6d656e.PNG)
![Production](https://user-images.githubusercontent.com/60824426/101718692-bf49d580-3a6f-11eb-926a-499bf5ac66be.PNG)

Sincerely,
Cesar M.

**Comment by CrimsonSIS** [comment]
Remember, you need to redirect to 

> ....e2/p3/public

:-)

**Comment by susanBuck** [comment]
@CrimsonSIS Hit the nail on the head. : ) 

Ref: https://hesweb.dev/e2/notes/php/frameworks/setup

> Note how we’re setting the DocumentRoot/Directory to the **public** folder within our new application. This restricts the files that the browser has access to and prevents it from directly accessing the server-specific files in the root of our application.

Example virtual host for a framework-based project:

```
<VirtualHost *:80>
    ServerName zipfoods.loc
    DocumentRoot c:\xampp\htdocs\e2\zipfoods\public
    <Directory c:\xampp\htdocs\e2\zipfoods\public>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>
```

**Comment by marroquin7** [comment]
Hi Professor,
I tried that before and tried it again now, and I got the error on the image.
![Error](https://user-images.githubusercontent.com/60824426/101719648-c2de5c00-3a71-11eb-9332-a54e0526d5b8.PNG)
![Virtual](https://user-images.githubusercontent.com/60824426/101719654-c671e300-3a71-11eb-9246-c4c028b9ae35.PNG)

**Comment by susanBuck** [comment]
Those are two separate issues - the "Forbidden" error was because of the document root pointing to the wrong directory (not public/). 

This second issue (file_put_contents error) is because the application does not have write permissions to the cache directory. Here is the section of the "Deploy to Production" notes that addresses this: https://hesweb.dev/e2/notes/php/frameworks/deploy#permissions

**Comment by marroquin7** [comment]
Great, I can access my application now. Thanks!
I am sorry, for bugging you. My URLs are broken on Production, but there are running fine on the local server. 
For example, my /records URL to see the history games appears as Not Found, same for the other pages except for the home page. 
Is that something you can provide some advice on?

Thanks,
Cesar M

**Comment by susanBuck** [comment]
Excellent - glad you're making progress. : )

It sounds like routing is not working on your production server. I suspect maybe this step was not completed:
https://hesweb.dev/e2/notes/php/frameworks/deploy#prep-digitalocean

Specifically, this part: 
![image](https://user-images.githubusercontent.com/237711/101721100-2d44cb80-3a75-11eb-945c-7ab2a712804f.png)

**Comment by marroquin7** [comment]
Thanks! that is working now. 
But my database is not displaying the results on production now. :( I made sure the dabase name is same for production and local, but no luck. My history page is totally empty despite the game runs fine. 
![game](https://user-images.githubusercontent.com/60824426/101723504-67fd3280-3a7a-11eb-9db6-34a6de4d3da4.PNG)
![history](https://user-images.githubusercontent.com/60824426/101723512-6b90b980-3a7a-11eb-936c-ca5aa236757b.PNG)
![database](https://user-images.githubusercontent.com/60824426/101723521-70ee0400-3a7a-11eb-914a-508e404f039c.PNG)

**Comment by marroquin7** [comment]
I ran migration in the local server to test it and played a couple of rounds, and it works fine. Unfortunately, it is not the same story for the production server. I followed your steps on how to set up p3, but I'm still stuck with the database problem :( . 
![local](https://user-images.githubusercontent.com/60824426/101723959-6849fd80-3a7b-11eb-9bac-984f8989cf47.PNG)
![record](https://user-images.githubusercontent.com/60824426/101723966-6c761b00-3a7b-11eb-97b8-d42523575412.PNG)

**Those images are for the local server

**Comment by marroquin7** [comment]
*UPDATE
Found the issue!
My timestamp variable is null in production, and I'm pulling my records using the timestamp variable.
Thanks for your help!

**Comment by susanBuck** [comment]
Hi @marroquin7 -

Did some digging into this issue. 

In your [PlayController file in the playgame method](https://github.com/marroquin7/e2/blob/master/p3/app/Controllers/PlayController.php#L42), when you insert the round details into the database, you're not setting a value for the timestamp column:

```php
$data =[
            'player' => $player,
            'computer'=> $computer,
            'outcome'=> $outcome,
        ];
```

When we run this locally, MySQL is configured such that any new rows in a table with a **timestamp** type column will automatically have a timestamp generated for it. The result is that even though you're not specifying the timestamp, one is generated for you.

As a result, everything works expected locally when you go to your records page and print out each record, labeling each link with the timestamp:

![image](https://user-images.githubusercontent.com/237711/101797397-fd7adf80-3ad7-11eb-9d01-bda6ce461603.png)

On production, however, MySQL is configured differently and so we don't get this "auto timestamp generating" behavior. **The result is that for each round you're recording, the timestamp is blank.** And because of this, when you try to display each round by it's timestamp, we're not seeing anything on the page:

![image](https://user-images.githubusercontent.com/237711/101797791-69f5de80-3ad8-11eb-8b58-05f7931d7fc3.png)

However, if you look at the underlying source code, you can see each round is there - we just don't see it on the page because there is no timestamp value:
![image](https://user-images.githubusercontent.com/237711/101797701-52b6f100-3ad8-11eb-934b-6617b97ba995.png).

This is one of those confusing edge cases for a difference in server configurations can cause the same exact code to work as expected in one environment but not another.

To fix the issue, I suggest updating your code so that the timestamp is explicitly set:

```php
$data =[
            'player' => $player,
            'computer'=> $computer,
            'outcome'=> $outcome,
            'timestamp' => date('Y-m-d H:i:s')
];
```

**Comment by susanBuck** [comment]
Looks like we arrived at the problem at the same time. 

Glad it's all sorted out.
