### ISSUE TITLE
Domain Issue - harvardtnproject.me

### ISSUE THREAD

**Issue by trnason** [susanBuck/e2-fall20#13]
Hi Class,

I am having an issue where when I go to me domain (harvardtnproject.me) I get an error that says "There isn't a GitHub pages site here." 

I have attached screenshots. Appreciate the help! 

![Screen Shot 2020-09-14 at 5 00 29 PM](https://user-images.githubusercontent.com/52473207/93142521-d022bf00-f6ab-11ea-8f55-e87ed0c4ddbe.png)

![Screen Shot 2020-09-14 at 4 53 22 PM](https://user-images.githubusercontent.com/52473207/93142072-ebd99580-f6aa-11ea-96d0-32006fa70a31.png)

![Screen Shot 2020-09-14 at 5 02 24 PM](https://user-images.githubusercontent.com/52473207/93142676-1bd56880-f6ac-11ea-9f23-605c55b9b289.png)

**Comment by susanBuck** [comment]
Hi @trnason -

It looks like the IP address (192.30.252.153) is for Github Pages. This may have been pre-configured if you created a domain via <https://nc.me>, as they provide an option to set up a site via Github Pages (there's a blurb about this in the [notes here...](https://hesweb.dev/e2/notes/production-server/production-domains#record-1-main-domain)).

If that's the case - update your DNS settings so the A record points to the **IP address of your DigitalOcean server** instead of the Github Pages IP address.

If that doesn't do the trick, let me know.

**Comment by trnason** [comment]
That worked! Appreciate it so much!
