### ISSUE TITLE
$ cat e2.pub 

### ISSUE THREAD

**Issue by deleonl4** [susanBuck/e2-fall20#26]
Following part 5 of this week's videos, I tried to copy the SSH key within `e2.pub` to connect my computer to Digital Ocean via the SSH but when typing the concatenate command in terminal to pull up the document, I received the following errors. I also noticed the `$` was replaced with `~ %`. It seems like some setting was changed...I did see a prompt within terminal and followed it earlier (see screenshot 2)

1. <img width="587" alt="Screen Shot 2020-09-17 at 9 54 09 PM" src="https://user-images.githubusercontent.com/47702390/93546223-636c2680-f930-11ea-8fa2-b4108957a50a.png">

2. <img width="585" alt="Screen Shot 2020-09-17 at 5 02 11 PM" src="https://user-images.githubusercontent.com/47702390/93546924-ec379200-f931-11ea-992e-38800a98a403.png">

**Comment by deleonl4** [comment]
Further troubleshooting helped me figure out how to change my settings back to bash shell (https://support.apple.com/en-us/HT208050). Got the SSH key, all set. Closed.

**Comment by susanBuck** [comment]
Glad you got to the bottom of it @deleonl4. : )

Some background: the latest Mac OS (Catalina) switched from using **bash** to a program called **zsh** for its backend used in Terminal.

They're very similar, and for all our uses in this course, they should work interchangeably. (I've only run into issues in regards to some configurations, which I've described in this thread: https://github.com/susanBuck/e2-fall20/issues/15).

Let's talk about some of the errors you received when running in *zsh* though.

From your first screenshot, I can see you ran this command:

```
$ /Applications/XAMPP/xamppfiles/htdocs
```

That is not actually a command, but just a directory path. Typically, when working with a directory path it's prefixed by some command. 

For example, this would change into the directory (using the `cd` or change directory command):

```
$ cd /Applications/XAMPP/xamppfiles/htdocs
```

This would show the contents of the directory (using the `ls` or list command):
```
$ ls /Applications/XAMPP/xamppfiles/htdocs
```

When using zsh, it appears that if you try and run a directory path as a command it reports back permission denied. I'm assuming this is because it attempts to treat that directory as an executable, which it is not:

![image](https://user-images.githubusercontent.com/237711/93613736-41f65380-f99f-11ea-9288-46354a7c2abd.png)

If we contrast this to when Terminal is running with bash, we're told *"[path] is a directory"*:

![image](https://user-images.githubusercontent.com/237711/93613820-59354100-f99f-11ea-84dd-b549bd649a1e.png)

Takeaway: Regardless of the different output/error message in bash vs. zsh, running `/Applications/XAMPP/xamppfiles/htdocs` is not a valid command by itself.

From what you described, it sounds like you switched to zsh, then back to bash. I think this is good, and you should stick with bash, as that's what I'm using so it'll provide for the most consistent experience to avoid confusion. Down the road, you may want to consider updating to zsh, but it's not essential right now.

Circling back to your original issue of trying to view e2.pub - I don't see any commands in the screenshots you shared that show attempts at this, so I can't speak specifically to why that would have failed (in either bash or zsh). If you run into that problem again, let me know. : )

**Comment by deleonl4** [comment]
This is really helpful. I Agree, sticking with bash is better, especially since I already started using it. Thank you for explain that I need to add the command before like cd or cat etc. It's something I have to remember and get used to. 

Also, in regards to e2.pub would `$ cat e2.pub` not be appropriate for viewing the public key in the screenshot below?

<img width="587" alt="93546223-636c2680-f930-11ea-8fa2-b4108957a50a" src="https://user-images.githubusercontent.com/47702390/93621061-06608700-f9a9-11ea-91de-9f54acaec0e8.png">

**Comment by susanBuck** [comment]
Trying to open the file without the full path to the file (`cat e2.pub`) will only work if **you're currently in the directory where `e2.pub` exists.**

So you'd first want to run `cd ~/.ssh` to change directories into your SSH directory; *then* run `cat e2.pub`.

Example:

![image](https://user-images.githubusercontent.com/237711/93621454-93a3db80-f9a9-11ea-9455-68d4104ccf4b.png)

Alternatively, if you include the full path when using cat, it should be able to open the file from within any directory.

For example, here's what it looks like if I'm in my htdocs directory and I try to open the `e2.pub` file using the full path of `~/.ssh/e2.pub`:

![image](https://user-images.githubusercontent.com/237711/93621555-ba621200-f9a9-11ea-81d2-4f4c587da764.png)

**Comment by deleonl4** [comment]
Got it. Thank you so much for explaining! I will keep practicing this week's material and keep working on my "cheat sheet" so I can fully grasp all of the commands and their results.

**Comment by susanBuck** [comment]
np! Command line is a tricky beast at first. You'll get it with practice!
