### ISSUE TITLE
Not getting error 'red underline' in VSCode

### ISSUE THREAD

**Issue by pranjal-joshi97** [susanBuck/e2-fall20#31]
Hello, 
I'm not getting the usual red underline indicating an error. For example, I omitted a '  ;  '  at the end of line 7 but not getting any indication of an error. 
![image](https://user-images.githubusercontent.com/42822597/93740468-bd146f80-fc14-11ea-8385-87d95d3359d6.png)

Any idea why this is happening? I don't want to miss any errors when it comes to coding the projects. 

Thanks! 
Pranjal

**Comment by trnason** [comment]
Good Morning! On mine, the red line only appears when I hit save.

**Comment by pranjal-joshi97** [comment]
Unfortunately, it doesn't appear even after hitting save for me. The only things that appear after hitting save are the blue-green side bars which indicate new changes, etc.

**Comment by susanBuck** [comment]
Hi @pranjal-joshi97 -

Any chance you've seen/are seeing this message:

![image](https://user-images.githubusercontent.com/237711/93782049-14f0ad80-fbf8-11ea-9aa6-8276441de2f1.png)

If so, that could be the reason it's not checking your PHP code for errors.

To resolve this, open your VSCode settings file - I believe you're on Windows so that path would be:

```
%HOME%\AppData\Roaming\Code\User\settings.json
```

In this file, add the line `"php.validate.executablePath": "c:/xampp/php/php.exe"`. E.g. 

```
{
    # ...Other configs might be here...
    "php.validate.executablePath": "c:/xampp/php/php.exe" 
}
```

This tells VSCode to use the php install that comes with XAMPP as its executable.

After making that change, see if it works. If not, let me know and we can try some other things.

(Also, confirming @trnason's note - you do have to save the file before seeing the red error line indicator.)

**Comment by pranjal-joshi97** [comment]
@susanBuck it worked! Thanks so much for your help :)

**Comment by susanBuck** [comment]
Glad it's sorted out! I'll mention this in this week's lecture as I suspect other students are having the same problem.

**Comment by susanBuck** [comment]
Just as reference for anyone else reading this thread - I published a new note set that addresses this issue and the issue described in thread #34.

I'll cover it in this week's lectures, but you can find the info here: https://hesweb.dev/e2/notes/misc/vscode-and-php

**Comment by chuckac** [comment]
> @susanBuck it worked! Thanks so much for your help :)

Ditto -- was having the same issue.  Thanks!

**Comment by mborjon** [comment]
@susanBuck What would the fix be on macOS? Thanks.

**Comment by susanBuck** [comment]
Hi @mborjon - Check out https://hesweb.dev/e2/notes/misc/vscode-and-php - it covers both Mac and Windows paths. Let me know if it doesn't work on your end!

**Comment by susanBuck** [comment]
Closing this thread, but feel free to start a new one if anyone is still having issues with VSCode configs.
