### ISSUE TITLE
Still getting standard Digital Ocean Page when visiting domain

### ISSUE THREAD

**Issue by walshkelsey** [susanBuck/e2-fall20#32]
I am still getting the standard Digital Ocean set up page when visiting my domain. I tried all the troubleshooting tips on the notes page but it is still not showing the right text. I'm wondering if I had an error occur somewhere in the cloning process, as that is where I has the most trouble. 

Here are my DNS settings: 

![Screen Shot 2020-09-21 at 7 21 00 PM](https://user-images.githubusercontent.com/69866282/93830955-9ddf0780-fc3f-11ea-9ca1-855d38abfa3c.png)

And here is what terminal is showing for the contents of /var/www/html/

```
root@walshe2:~# cd /var/www/html/
root@walshe2:/var/www/html# ls
e2  index.html
root@walshe2:/var/www/html# 
```
And when I pulled the index.html file in nano, this is what it contained: 

```                                                    
<html>
  <head>
    <style>
      body {
        font-family: ProximaNova;
        font-size: 15px;
        font-style: normal;
        font-stretch: normal;
        line-height: 1;
        letter-spacing: normal;
        margin: 0;
      }

      .button {
        border-radius: 3px;
        background-color: #0069ff;
        color: #ffffff;
        display: flex;
        flex-direction: column;
        height: 48px;
        justify-content: center;
        text-decoration: none;
        width: 148px;
      }

      .content {
        align-items: center;
        border: solid 2px #f1f1f1;
        border-radius: 3px;
        display: flex;
        flex-direction: column;
        margin: 32px auto;
        padding: 32px;
        text-align: center;
        width: 960px;;
      }

      .copyright {
        color: #99999999;
        font-size: 13px;
```

The contents is what is making me think I went wrong with the cloning. Any idea on how to troubleshoot from here?

**Comment by susanBuck** [comment]
Hi @walshkelsey -

Try replacing all the content in that `/var/www/html/index.html` file with some example text like I did in lecture...

The text I used was:

```
Hello from my DigitalOcean server!
```

Which is why when you visit my main domain <http://hesweb.xyz> you see that message:

![image](https://user-images.githubusercontent.com/237711/93834174-e949e380-fc48-11ea-8b56-522be9dcbe98.png)

Keep in mind, you don't *have* to do this step - it's okay if your main domain points to that default DigitalOcean page all semester long, as what we're really concerned about is the subdomains we're setting up for our individual applications.
The point in doing this step is simply just to understand that the main domain is pointing to the content in `/var/www/html/index.html`.

After you update `/var/www/html/index.html`, let me know if that does/does not change the content at http://kwalsh12.me as expected.

After that, you'll want to work on getting your subdomains working (e.g. http://practice.kwalsh12.me and http://e2p1.kwalsh12.me) - so let me know if you get stuck there as well.

_PS: Re: your DNS settings: they look good, but I suggest deleting that first _"URL Redirect Record"_. We don't need it and I don't want it causing any issues/confusion._

**Comment by susanBuck** [comment]
Following up on this thread, I see http://practice.kwalsh12.me is working as expected. 👍

Let me know if you're still having any issues with the main domain or other subdomains.

**Comment by walshkelsey** [comment]
Closing due to solving issue.

For some reason it was not letting me save the index.html file, but my subdomains were working as expected. I re-started terminal, updated the index.html file while in sudo and was able to make the change.

**Comment by susanBuck** [comment]
Glad it's sorted out @walshkelsey. 👍
