### ISSUE TITLE
Assignment 3 Scores muted

### ISSUE THREAD

**Issue by CrimsonSIS** [susanBuck/e2-fall20#33]
No biggie-wiggie but scores to **Assignment 3** are muted.

It is a closed assessment so it would be nice to have the autograder provide feedback.

JIC we unintentionally respond incorrectly. 

![image](https://user-images.githubusercontent.com/53196073/93899152-066ec880-fcc2-11ea-8951-a7a3fd1daa99.png)

:-)

**Comment by susanBuck** [comment]
Hi @CrimsonSIS  -

This is intentional, and is actually how assignments should have been configured from the start. :-) 

In my other course, Canvas *did* mute all assignments automatically from the start. Based on this, I assumed the same was happening in this course, but I was wrong. That's why in Assignment 1 and 2 you could see an auto-grade - and I even made an announcement about this in the Week 2 lectures because a couple students were panicked by the low score they saw from the auto-grader (since it didn't account for the open-ended questions).

It was only when I realized the assignments weren't muted that I understood why the auto-grading was showing at all. 

Now all assignments are muted until I complete grading.

If they're not muted, students see an auto-grade, and they can use this information to deduce if they didn't get all the multiple choice questions correct. Because I allow multiple attempts, they can then game the system by just retaking the assignment over and over again until they get them all correct. The end result is I then can't actually tell which questions students are struggling with.

I don't intend/design the assignments to be tricky or difficult. Typically, if one follows the notes and watches the lecture videos, they can score very well on the assignments. Given this, I think it's reasonable to expect students to answer the questions to the best of their abilities, and wait until grading is complete to see their final assessment.

Make sense/seem fair? : )

**Comment by CrimsonSIS** [comment]
DMed you with some thoughts on this. :-)
