### ISSUE TITLE
VSCode "Format on save" not working for me

### ISSUE THREAD

**Issue by alysonann** [susanBuck/e2-fall20#34]
The "Format on save" isn't working for me on my Mac. I don't have an "Editor: Save on format Timeout" setting, as in the forum screenshot and video. I have played with the "Files: Auto Save" settings and none of those seem to make a difference. I do have "Editor: Format on Save Mode" with two options--"file" and "modifications," and neither of those makes it work. I've also tried selecting an option in a "Editor: Default Formatter," but that was "null" in the video so that shouldn't be it...

Excited to get this working--wish I knew it was an option in the past! :)

<img width="717" alt="Screen Shot 2020-09-22 at 6 07 26 PM" src="https://user-images.githubusercontent.com/31620333/93942598-ba8e4480-fcfe-11ea-9e6f-b6dd1d84f0f1.png">

**Comment by susanBuck** [comment]
Hi @alysonann -

Ah, apologies for the confusion there. I forgot the auto-formatting in PHP files require an extra plugin which I did not cover in the VSCode notes/video.  Sometimes it's hard to tell what is default behavior in VSCode vs. what is happening because of a plugin. : )

I'll address this in this week's upcoming lecture to clear up any confusion -

In the meantime, here's a set of notes where I describe how to set up the necessary plugin - you want to focus in on the section *VSCode - PHP CS Fixer* - https://hesweb.dev/e2/notes/php/code-style#vscode-php-cs-fixer

**Comment by susanBuck** [comment]
Just as reference for anyone else reading this thread - I published a new note set that addresses this issue and the issue described in thread #31.

I'll cover it in this week's lectures, but you can find the info here: https://hesweb.dev/e2/notes/misc/vscode-and-php

**Comment by alysonann** [comment]
Thank you! I'm all set with both of these. (I think we're supposed to close things, so I'm closing this, but apologies if I should wait for the instructor!)
