### ISSUE TITLE
http://localhost/e2/practice/week4.php  -  Access Forbidden

### ISSUE THREAD

**Issue by deleonl4** [susanBuck/e2-fall20#45]
I was following Week 4's video example and ran into issues when trying to access my week4.php file (screenshot below). 

![Screen Shot 2020-09-29 at 10 35 23 PM (2)](https://user-images.githubusercontent.com/47702390/94637256-1760a080-02a5-11eb-883a-e1ddba7d3b37.png)

I restarted Apache in XAMPP and tried troubleshooting using the[ notes](https://hesweb.dev/e2/notes/local-server/local-domains#step-3-create-a-new-host) but when trying the `/Applications/XAMPP/xamppfiles/etc/httpd.conf` command in terminal, I was given a similar permission denied error (screenshot below):

<img width="587" alt="Screen Shot 2020-09-29 at 10 39 15 PM" src="https://user-images.githubusercontent.com/47702390/94637239-0ca60b80-02a5-11eb-907c-4dd3697b885e.png">

Has this happened to anyone else?

**Comment by susanBuck** [comment]
Hi @deleonl4 -

From your browser screenshot, it looks like you're trying to access the work via `http://localhost/e2/practice/week4.php`.

Do you have a `practice.loc` local domain set up? If so, you'd want to access the work via `http://practice.loc/week4.php`.

**Regarding trying to edit `/Applications/XAMPP/xamppfiles/etc/httpd.conf`:**

It looks like the command you've run is just the path to this file:

```
$ /Applications/XAMPP/xamppfiles/etc/httpd.conf
```

You want to prefix that path with some command, such as Nano, in order to open/edit it. E.g.:

```
$ nano /Applications/XAMPP/xamppfiles/etc/httpd.conf
```

That being said - are any of your local domains working (e.g. practice.loc or e2p1.loc)? If so, you should not need to edit httpd.conf - since we can assume it is already correctly reading from your Virtual Hosts config file if at least one local domain is functioning.

If one of your local domains is working, but another is not, the files you'd want double check/revisit are:

+ `/Applications/XAMPP/etc/extra/httpd-vhosts.conf` Where Virtual Hosts are configured
+ `/private/etc/hosts` How local domains are mapped to your local server

**Comment by deleonl4** [comment]
You're right, I accessed it right away. Thank you!! All others are working perfectly.
