### ISSUE TITLE
Project 2 - Having two submit buttons within a form were not able to show two different results 

### ISSUE THREAD

**Issue by tatthung** [susanBuck/e2-fall20#50]
Dear @susanBuck usan, Classmates,

I am having some issues with two submit buttons for my Project 2. I am trying to build a player vs computer rock-scissor-paper game. The human player has to pick a move (rock, scissors or paper) based on the radio buttons available before hitting the submit button (I call this the first button). However, in the event of a 'tie', both players (human and computer) get to versus each other in round 2 with their second-hand (it is actually repetition of the first round, above where the human player get to pick one of the 3 options agai before hitting the second submit button, and publish the round 2 results). The first part of the game is possible, until I reached the second part of the game (round 2) - the second button reset the round 1 results instead of round 2. I was wondering if there are some codes that could assign submit button 2 to control and publish the results of round 2 (instead of round 1).

I tried some simple codes suggested by StackOverflow, but all of them seem to have failed me, or maybe I work on those codes in the wrong perspective. Some of the codes include PHP side:

```
<?php
$submitbutton = $_POST['sb'];
?>
```

or

```
switch ($_POST['click']) {
    case 'clickedOne':
        // first pressed
    break;
    case 'clickedTwo':
        // second pressed
    break;
    default:
        // something wrong
    break;
}
```

Here is my Github repository URL: > https://github.com/tatthung/e2/tree/master/p2 and my Project 2 URL is > http://e2p2.tatthung.me/

Many thanks,
Tatt

**Comment by susanBuck** [comment]
Hi @tatthung -

This is an interesting problem as it really forces us to think through both the game logic and the "state" of the application over multiple iterations/submissions.

However, I think you may be overcomplicating things by having a separate set of inputs if it's a tie:

![image](https://user-images.githubusercontent.com/237711/95218716-903e8b80-07c2-11eb-9811-668786652f9d.png)

Why can't we just use the same inputs again, like this:

![image](https://user-images.githubusercontent.com/237711/95218931-cc71ec00-07c2-11eb-86f4-e715e8b7792d.png)

Would that work for what you're envisioning?

**Some other tips/notes from scanning through your code:**

Code such as the following is not producing any output and should not be a in a view file:

```php
$playerASecondHand = null;
$playerBSecondHand = null;
$winnerTwo = null;
```

Instead of having 3 separate *if* blocks to look for a tie by comparing each player's throw against a move (rock, paper, scissors)...

```php
# If both playerA and playerB threw rock...
if ($playerA == $moves[0] and $playerB == $moves[0]) {
}

# If both playerA and playerB threw paper...
if ($playerA == $moves[1] and $playerB == $moves[1]) {
}

# If both playerA and playerB threw scissors...
if ($playerA == $moves[2] and $playerB == $moves[2]) {
}
```

Have a single *if* block that simply looks and see if the player's move match (indicating a tie):

```php
# If playerA and playerB threw the same move
if ($playerA == $playerB) {
}
```

**Comment by tatthung** [comment]
Thanks a lot @susanBuck, actually you are right, I felt like I'm overcomplicating things by introducing the second hand. Also thank you for your suggestion to further simplify my codes! I will modify to single if block! Thank you.
