### ISSUE TITLE
Project 1 share thread

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall20#51]
Hi everyone,

I wanted to start a thread where you all could share your Project 1's.

In reply to this thread, please share the following:

1. The link to your P1 on production (so everyone can view it)
2. The link to your P1 on Github (so we can see the code behind it)
3. A note (or more) about your experience building the project. Example:
    + Was there some part you got stuck on? If so, how did you get past the issue?
    + Did you use a technique, function, etc. that was unique from what we saw in lecture?
    + Did you start with one game idea but end up pivoting to another? If so, why?
    + Was there some aspect of the project/game that you had hoped to tackle but didn't get to?
    + Was there anything you learned/encountered for the first time in regards to programming?
    + Etc.

**Comment by CrimsonSIS** [comment]
1. The link to your P1 on production (so everyone can view it)\
\
See http://e2p1.crimsonsis.me (Project 1 URL)

2. The link to your P1 on Github (so we can see the code behind it)\
\
See https://github.com/CrimsonSIS/e2/tree/master/p1

3. A note (or more) about your experience building the project.\
\
I initially forgot to upload the **README.md** file and put **index.php** and **index-view.php** files under the root, instead of the **e2/p1** subdirectory. (Clicked into _Assignment 3_ accidentally and had to back-out with the clock ticking.)\
\
Manually fixed that by changing the directory structures in _GitHub_ from my iPhone (as the _Termius SSH_ app display is too dinky and was away from computer). \
\
Will do a _git pull_ to synch after grading so as not to meddle with time/date stamp.\
\
Wanted to do _Tic-Tac-Toe_ with realtime oppositional user inputs but didn't know how to persist values between sessions. Now that we've covered that in lecture, may give it a shot.\
\
Am still internalizing the syntax of the language, so needed to reference your logic for echoing the contents of the results array:


>         <?php
>             foreach ($results as $key => $value) {
>                 echo "$value";
>             }
>         ?>

**Comment by maqboolk** [comment]
Prod URL : http://e2p1.hesmk.me/

Github : https://github.com/maqboolk/e2/tree/master/p1

**Comment by trnason** [comment]
Prod URL: http://e2p1.harvardtnproject.me/
Github: https://github.com/trnason/e2/tree/master/p1

**Comment by mborjon** [comment]
Hello,

1. Link to P1 on production:
http://e2p1.zorrodigital.me

2. Link to P1 on Github:
https://github.com/mborjon/e2/tree/master/p1

When I went to finish the logic of my game, I had to go back and rewatch a few videos because all the var_dumps confused what I really needed within my code.  I also realized that I need to better about having final final done on local first before it goes to Git then production or else I'll have to redo all the commits, etc. again to make any changes show up on production.  

Regards,
-Melinda

**Comment by tatthung** [comment]
Dear Guys, @susanBuck,

1. The link to your P1 on production (so everyone can view it)
`http://e2p1.tatthung.me/ `

2. The link to your P1 on Github (so we can see the code behind it)
`https://github.com/tatthung/e2/tree/master/p1`

3. A note (or more) about your experience building the project. 
This is a modified version of the rock-scissors-paper game between 2 computer players, where in the event of a tie between the 2 players, there will be a tiebreaker round where the system will randomly roll a move for both the computer players and publish the results in the following line.  Fortunately i managed to tackle what I wanted to build with the `if and else` loop.

Considering this is the first time building a game with PHP, although I am satisfied with what I have built and managed to build what I wanted, but i believe there are simpler ways (which I have also found out after the dateline of this project, thanks to @susanBuck https://github.com/susanBuck/e2-fall20/issues/50) to build the game conditions with if and else loop, rather than listing every condition.

For example
```
if ($playerA == $moves[0] and $playerB == $moves[0]) {
    $winner = 'Tie';
} elseif ($playerASecondHand == $moves[0] and $playerBSecondHand == $moves[0]) {
    $winnerTwo = 'Tie';
} elseif ($playerASecondHand == $moves[0] and $playerBSecondHand == $moves[1]) {
    $winnerTwo = 'Player A';
} elseif ($playerASecondHand == $moves[1] and $playerBSecondHand == $moves[1]) {
    $winnerTwo = 'Tie';
} elseif ($playerASecondHand == $moves[1] and $playerBSecondHand == $moves[2]) {
    $winnerTwo = 'Player A';

``` 

I could work something like this
```
if ($playerBSecondHand == $playerASecondHand) {
    # if there is a tie in the dice game
    $winnerTwo = 'Another Tie';
} elseif ($playerBSecondHand > $playerASecondHand) {
    $winnerTwo = 'You Won';

```

**Comment by kristysunnyd** [comment]
Hi everyone, 
1. The link to your P1 on production (so everyone can view it)
[http://e2p1.sunnykreme.me/](http://e2p1.sunnykreme.me/)

2. The link to your P1 on Github (so we can see the code behind it)
[https://github.com/kristysunnyd/e2/tree/master/p1](https://github.com/kristysunnyd/e2/tree/master/p1)

3. A note (or more) about your experience building the project. 
For this project, since it was my first time building a project with PHP, I wanted to start off simple and decided to create a Rock, Paper, Scissors game. However, after I finished and checked the code for the simple version of Rock, Paper, Scissors, I decided to spice things up by adding extra 'moves' based on the version of the game from the Big Bang Theory (tv show). Ultimately, I also wanted to add 'rounds' to the game but I didn't get enough time to get around to that.

**Comment by rlange2176** [comment]
Hi all,

For project 1, I did a slot machine simulator.
1. [Production URL](http://e2p1.beccalange.me/)
2. [GitHub URL](https://github.com/rlange2176/e2/tree/master/p1)
3. To sort through my array and make the fruit selections, I was originally using the shuffle function, but in looking at the PHP documentation, I discovered a new function called array_rand that achieved something similar:
`$fruit1 = array_rand($fruits, 1);`

**Comment by alysonann** [comment]
1. [http://e2p1.alysonann.xyz/](http://e2p1.alysonann.xyz/)
2. [https://github.com/alysonann/e2/tree/master/p1](https://github.com/alysonann/e2/tree/master/p1)
3. I just stuck to rock, paper, scissors for this project! I decided I didn't want to confuse myself by tackling a game I didn't know inside and out, and that dealing with cards seemed a bit daunting. At one point, in an `if`/`elseif` statement, I used `=` instead of `==` and was assigning a new value for a player's move rather than comparing. Honestly, until I caught the mistake, it was making me question everything I understood about random number generators and variables... It will be the first thing I check from now on! I was hoping to incorporate rounds (best of three), but ultimately found the arrays and pulling out information in my view file a bit too complicated. I'm looking forward to understanding multi-dimensional arrays a bit better and how to work with them going forward!

**Comment by scoutperry** [comment]
1. http://e2p1.scoutperry.me/
2. https://github.com/scoutperry/e2/tree/master/p1
3. Most of my struggles happened with learning command line and setting up the local server for the project. because of this, I picked a simpler game because I wasn't sure how was going to do using php for the first time. That seemed to go much smoother because I saw some similarities in to when I studied javascript. I think I will try a more complicated game for project 2

**Comment by pllealfunes** [comment]
HI guys here's my project 1,

1. url: http://e2p1.lefthandedcat.me/ 
2. github: https://github.com/pllealfunes/e2/tree/master/p1 
3. This was my first project in PHP and I wanted to do something simple so I chose the High Low Game. The thing I struggled with the most was figuring out if I was properly following the rules of the Separation of Concerns. I had to go over the videos many times to double check I was doing it right and I'm happy I was able to figure it out.

**Comment by chuckac** [comment]
Nice projects everyone.  Adding mine to the mix. 

[Production Link](http://e2p1.chuckac.me/)

[Github Repository](https://github.com/chuckac/e2/tree/master/p1)

**Comment by walshkelsey** [comment]
1. http://p1.kwalsh12.me/
2. https://github.com/walshkelsey/e2/tree/master/p1
3. Like several others, this was my first project in PHP. Most of my coding experience has been HTML basics on existing web pages (making things look pretty and fixing links) so I was excited to take a stab at this. I had a lot of fun with it, and once I got going it was very easy to figure it out and make updates as I went along. I decided to go with a simpler game just so I could really focus on the code without having to worry about game mechanics. I've also watched a LOT of Friends during quarantine, so I figured it would be a little fun to incorporate that as well.

**Comment by pranjal-joshi97** [comment]
1. http://e2p1.pranjaljoshi.me/

2. https://github.com/pranjal-joshi97/e2/tree/master/p1 

3. I really enjoyed this project, I had never built a game that had no user input and was randomly generated. Initially I had decided to go with a simple dice game where two players roll their own dice and whichever player lands on the highest number wins. But after coding that out, I wanted to challenge myself and see how I could take the game to the next step. So I made some modifications to it using a Count function. We hadn't covered it in class so I used the PHP Manual. This new version had two players roll their dice and whichever player rolled a 6 in the least number of rounds won! One issue that I faced was that the program wasn't properly recognizing a tie so I had to $var_dump the results using the different variables in the count function (very experimental).
