### ISSUE TITLE
Problem with Subdomains

### ISSUE THREAD

**Issue by mborjon** [susanBuck/e2-fall20#54]
Hello,

When I was deploying my p2, something went wrong.  First time, after changing adding the new VirtualHost block at: /etc/apache2/sites-enabled/000-default.conf and restarting apache, my p2 was not directing to the subdomain and was just displaying the general 'Welcome to Digital Ocean' page.  I could see my p1 subdomain working correctly.  

After "troubleshooting," and deleting and re-entering the the new VirtualHost block at /etc/apache2/sites-enabled/000-default.conf...and restarting apache... I get a can't connect to either my p1 and p2.  Attached is a screenshot of my settings at /etc/apache2/sites-enabled/000-default.conf.

(p.s. It all works fine local)

Thanks,
-Melinda
<img width="892" alt="Screen Shot 2020-10-11 at 5 59 09 PM" src="https://user-images.githubusercontent.com/38201146/95695584-751db280-0bec-11eb-9751-105a3afac247.png">

**Comment by tatthung** [comment]
Dear @mborjon,

Did you set this up on namecheap.com?
![image](https://user-images.githubusercontent.com/10286253/95706258-f2970080-0c88-11eb-947b-a6b5f3c8b3f1.png)

**Comment by susanBuck** [comment]
@tatthung - Good suggestion. However, I think @mborjon's DNS settings are okay - the domain `zorrodigital.me` is resolving to the IP address 159.89.148.238 (I tested this by running the command `ping 159.89.148.238`).

It appears there's something wrong on the server end of things since none of the following will load:

+ http://159.89.148.238/
+ http://zorrodigital.me
+ http://e2p2.zorrodigital.me 

They all lead to this error:

![image](https://user-images.githubusercontent.com/237711/95756809-477c4c00-0c74-11eb-8cb5-701c1fd0934f.png)

@mborjon - **On your prod server, can you run the command `apachectl -S` and share the output? It will give us some debugging info about your Virtual Hosts setup.**

**Comment by mborjon** [comment]
Hello @susanBuck,

Here is the output.

Thanks,
-M
<img width="692" alt="Screen Shot 2020-10-13 at 11 24 18 AM" src="https://user-images.githubusercontent.com/38201146/95900378-a9a58180-0d46-11eb-85a3-d6c611a5d2d4.png">

**Comment by susanBuck** [comment]
@mborjon - Everything looks good in that output.

Would you mind if I poke around your server to see if I can figure out what's going on? 

You can give me access by following these instructions: https://hesweb.loc/e2/notes/appendix/instructor-server-access

**Comment by mborjon** [comment]
@susanBuck I added the key. Thanks!

**Comment by susanBuck** [comment]
Great! Confirming I can log in. Looking at the server now. Will report backs shortly what I find.

**Comment by susanBuck** [comment]
I restarted Apache (`service apache2 restart`) and all appears well now. You mentioned in your initial post you had done this - but maybe you had made some more changes to the Virtual Hosts config file and forgot to restart after? That's the only thing I can think of : )

Tested/working:
+ http://159.89.148.238
+ http://zorrodigital.me
+ http://practice.zorrodigital.me
+ http://e2p1.zorrodigital.me
+ http://e2p2.zorrodigital.me

**Comment by mborjon** [comment]
Thanks! Weird, I restarted a few times. The only thing that happened since was I did a pull for my final e2p2 project update.
