### ISSUE TITLE
Project 2: Organizational Questions

### ISSUE THREAD

**Issue by CrimsonSIS** [susanBuck/e2-fall20#56]
Hi!

**Background**

Making headway on _Project 2._ I'm doing a two player interactive _Tic-Tac-Toe_ game. 

Did a **repl** at https://repl.it/@jdcole/TicTacToe#main.php to work out the logic. It works from the **repl** console. Try it out to see the objective.

Working on the separation of concerns organization of the controller/view/process modules for the web version. Doing the equivalent of the console readline with form input. No issues with the basic logic of that...

See https://github.com/CrimsonSIS/e2/tree/main/p2 .

**Questions**

1. The **$board** array is in **index.php** because it changes in subsequent iterations. Also, I want to print it out in **index-view.php** as an example in the opening gambit. This is "computational" and I know we're not supposed to put stuff like that there, but I don't see where else to put it.
2. Is there a way to hide the user defined functions in a library so they can be called (like an include)?
3. I use the **print_board ($board)** call in _index-view.php_ for the preliminary display. Is that kosher? I can hard code it with php code islands, but that seems cumbersome, and I need that first call to display the initial configuration of the board, then transition states, so don't want to duplicate logic.
4. Should I pass **$board** in the **$_SESSION** variable? I initialize it in _index_ and can reference it in _index-view_ without passing it explicitly.

Enjoying the class immensely!

:-)

![DGMD-2-Tic-Tac-Toe-Questions](https://user-images.githubusercontent.com/53196073/96023618-b1395900-0e20-11eb-9701-44a6be049fea.png)

**Comment by susanBuck** [comment]
Hi Jerald - Good (and clearly written!) questions. :-)

To dig into things, I want to first address how you're defining your board:

```php
$board = array(
        "1"=>"1", "2"=>"2", "3"=>"3",
        "4"=>"4", "5"=>"5", "6"=>"6",
        "7"=>"7", "8"=>"8", "9"=>"9"
    );
```

I suggest rewriting it as follows:

```php
$board = ['1', '2', '3', '4', '5', '6', '7', '8', '9'];

# This will result in an array where the 0th position value is `1`, the 1st position value is `2`, etc.
```

Reasons:
1. In this scenario, there's no need to create an associative array with explicit keys as you've done, since you just need keys that are an incrementing count of values in the array. Let PHP do that for you.
2. In my version the first "cell" will be at key position 0. In your version, it would be at key position 1. In programming we typically start counting at 0. It's counterintuitive to how we usually count things in the "real world" (starting at 1) but it's a practice I highly recommend getting used to, because it's the standard you'll see in programming.
3. You can define an array using the `array()` function, but it's more conventional now-a-days to just use the square brackets style (`[]`).

Ok, with that new `$board` in mind, let's talk about how to display/output it in the view...

I don't think this needs to be done via a function, as evidenced by the fact that **you only actually invoke the function once in the file**. If you were trying to print the board multiple times on a simple page load, then we'd want to look at "functionalizing it" to avoid repeat code.

As is, I think we can just program your view to output whatever `$board` currently is, and with each submission of the page, `$board` is updated, and the view is regenerated with the new `$board`. (This is assuming I'm understanding the program flow you've designed - let me know if I'm mistaken : )

Another optimization I'd make to the output of your `$board` is removing the need for `$square_count` to determine when a new row needs to be made. As it is used now, you have to do things like initialize it (`$square_count = 0;`) and increment it (`$square_count++;`) - these are all statements that clutter up the display code.

As an alternative, we can simply look at our keys as we iterate through the board, and when we hit key 3 or 6, make a new row:

```php
<table>
    <tr>

        <?php foreach ($board as $cell => $value) { ?>

            <?php if ($cell == 3 or $cell == 6) { ?>
                </tr><tr> <!-- Start a new row -->
            <?php } ?>

        <td><?php echo $value ?></td>
        
        <?php } ?> <!-- end for loop -->

    </tr>
</table>
```

To address some of your other questions:

> Is there a way to hide the user defined functions in a library so they can be called (like an include)?

Yup! You could create a separate file, let's say `library.php`, that can then be included (via a `require` statement) wherever you want to use code from that file. Just like we how we include our view files from our controllers:

```php
require 'library.php';

# Once that file is required, we could use any functions that are defined in it
```


> Should I pass $board in the $_SESSION variable? I initialize it in index and can reference it in index-view without passing it explicitly.

I think you're going to want to, because I'm assuming that with each "play"/submission, `$board` gets updated with new values, yes?

**Comment by CrimsonSIS** [comment]
Hi Professor Buck:

Thanks for the rapid response. I actually started with that representation, numbered from zero. (The chair of the Computer Science Department was always in Room 0. (Ha!))

The reason I chose an associative array was that I wanted to use the Vanna White approach. When a player marked a position, the **$board** contents at that position would convert to an **X** or an **O**, but still be addressable by their associated index [**1..9**].

We did a version of this in in high school using a 2D array and (row, column) coordinates in BASIC. Later did a version in  LISP for an AI course. While watching Wheel of Fortune last week it occurred to me that the board is really a vector and Vanna addresses squares by a label (color code in her case), not coordinates.

I think that is more in keeping with how people address elements of collections. Moreover, a lot of students have trouble with arrays--even if they grew up playing Battleship. Eliott Soloway wrote a paper in the '80 showing there is little transfer between learning array representations in programming languages and real life examples (like board games). Sobering thought--and his subjects were Yale undergraduates in programming 101 courses.

But we digress. So, here are two more questions:

1. Before learning about PhP sessions I was naively using global references to variables between modules and they worked. Are SESSION variables used only for form data in practice or should we stuff everything into them?
2. Should we always pass arrays by reference (**&$board**) even if the contents are not being changed by a function to reduce overhead? For example that is the general recommendation in C++ (with the caveat to beware of side-effects.)

I can brute force the version I have, but may bump into some additional issues with partitioning controllers and views.

Yes. Am updating the board like in Jeopardy to show transition states, so was planning to call **print_board** a 2nd time to show transition states while persisting the initial state.

:-)

**Comment by CrimsonSIS** [comment]
Ah! kewl. That blew my hair back.

![image](https://user-images.githubusercontent.com/53196073/96042156-ff5b5600-0e3a-11eb-8299-d4c990e92038.png)

**Comment by susanBuck** [comment]
> Before learning about PhP sessions I was naively using global references to variables between modules and they worked. Are SESSION variables used only for form data in practice or should we stuff everything into them?

Sessions are only necessary when you need to maintain data **between page requests** (including form submissions). 

> Should we always pass arrays by reference (&$board) even if the contents are not being changed by a function to reduce overhead? For example that is the general recommendation in C++ (with the caveat to beware of side-effects.)

This isn't necessary. I have an old note set on how variables are managed "behind the scenes" which I just put up that offers insight into why: https://hesweb.dev/e2/notes/php/garbage-collection.

> Yes. Am updating the board like in Jeopardy to show transition states, so was planning to call print_board a 2nd time to show transition states while persisting the initial state.

Having a little bit of a hard time envisioning what you're going after. Why don't you get it working using your print_board function (since it's already built) and then let me know, and I'll take a look at the code and see if I have suggestions about a different approach? :-)

**Comment by CrimsonSIS** [comment]
On it! Gracias!

**Comment by CrimsonSIS** [comment]
Good morning!

A couple of quick questions re/ Project 2.

See https://github.com/CrimsonSIS/e2/tree/main/p2 for the latest source.
See https://ctoxfordhouse.org/p2/index.php for a test deployment.

I was going to show transition states of the board (Initial --> Goal) but reorganized the logic so it refreshes after each session.

The initial load works fine. See "initial" illustration, below.

Subsequent loads convert the 9 element board array into a 1 element board array. See "subsequent" illustration, below.

In **index.php**, the **$board** array is initialized and stuck into the **$_SESSION** array. 
It passes to **index-view.php** and **print_board($board)** works fine.
After the form is submitted, **process.php** invokes. Two funky issues occur:
1. In the validation logic, **$board [$location] = $choice;** the Tic-Tac-Toe board is set to choice X or O at location 1..9. The variables **$choice** and **$location** pass correctly, but the assignment doesn't seem to work, though doesn't throw an error or a warning.
2. At the bottom, **$_SESSION** is prepared for return:

>     $results = [
>         'choice' => $choice,
>         'location' => $location,
>         'message' => $message,
>         'board' => $board,
>     ];
>     $_SESSION ['results'] = $results;

I put a string into the **'board'** element, and it returned fine, but when I assign the **$board** array to it, the board collapses down to the single element at **$location**.

I read that this is supposed to be permissible on _Slack_ (https://stackoverflow.com/questions/2306159/array-as-session-variable) and _phpRiot_ (http://www.phpriot.com/articles/intro-php-sessions/7). 

Also, on **index.php** refresh, it does not reinitialize the display unless I clear the buffer from the Developer Tools in Chrome. I can't null everything out in the session variable because the board is initialized there. 

May need a "New Game" button at the end or some other reinitialization trick. Assume there is a 'flush buffer' function to force that.

Clearly not a Jedi Master at this. Suggestions appreciated...!

:-)

![DGMD_2_TTT_Initial_Load](https://user-images.githubusercontent.com/53196073/96149537-6f1f1e80-0ed7-11eb-87cc-10d7b6e28439.png)

![DGMD_2_TTT_Subsequent_Load](https://user-images.githubusercontent.com/53196073/96149564-78a88680-0ed7-11eb-985d-dd5e0986e126.png)

**Comment by CrimsonSIS** [comment]
The functions **winner($choice, $board)**  and **is_available($location, $board)** are contingent upon having an **X** or **O** assigned to the board. That these functions are not working is an indication that something is altering the array. (They worked in a Repl test instance.)

**Comment by CrimsonSIS** [comment]
I also tried passing it by reference (commented out in **library.php**) but that didn't make a difference:

>     // function set_X_or_O($choice, $location, &$board)
>     // {
>     //     $board [$location] = $choice;
>     // }

Now just doing it by direct assignment in **process.php**:

> $board [$location] = $choice;

:-)

**Comment by susanBuck** [comment]
Hi @CrimsonSIS -

Looking through your code now...

When the form is submitted, assuming a valid `location` was entered, we get to this else branch in `process.php`:

![image](https://user-images.githubusercontent.com/237711/96166144-91bb3280-0eeb-11eb-884d-38202338ecb9.png)

The problem here is you're attempting to update `$board`:

```php
$board [$location] = $choice;
```

However, no where in `process.php` has `$board` been defined. As a result, this line is treating `$board` like a brand new array - and that's why you end up with a 1 element board array.

To fix, at the top of `process.php`, add this line to define `$board` and extract its values from the session:

```php
$board = $_SESSION['results']['board'];
```

Give that a shot and let me know how it goes.

**Comment by CrimsonSIS** [comment]
That worked! Thanks so much!

Now trying to figure out how to reset the board after a win or tie. Manually clearing the buffer in Chrome works.

Is there a PhP function I can attach to a New Game button to force that, or a 'stop session' that will force a clean start_session on next reload of **index.php**?

Also, according to https://www.php.net/manual/en/function.session-start.php, **session_start ()** _starts_ or _resumes_ a current session.

Should we routinely do a **session_start ()** at the top of each module (**index.php**, **index-view.php** and **process.php**)?

:-)

**Comment by CrimsonSIS** [comment]
Answered my 2nd question. It gives a redundancy warning and ignores it.

Just need to figure out how to terminate play after win or tie.

**Comment by CrimsonSIS** [comment]
It's up and working at http://e2p2.crimsonsis.me/.

Also posted to Canvas. Haven't figured out how to restart session once the game runs to completion, so just echoed a "Game over! message at the bottom. I also used echo statements in a few places in the view where I know I could just embedded raw HTML. Used code islands liberally but towards the bottom it was more intuitive to me to use a PhP code block or two.

Appreciate your help!

:-)

**Comment by susanBuck** [comment]
To clear an individual session value, set it to null. 

Ref: https://hesweb.dev/e2/notes/php/sessions

Example clearing an individual value from a session:
```php
$_SESSION['results'] = null;
```

Alternatively, if you want to clear all sessions, you can use [session_unset](https://www.php.net/manual/en/function.session-unset.php).

Project came out nice, good work @CrimsonSIS!

**Comment by CrimsonSIS** [comment]
On it full-tilt boogie...

**Comment by CrimsonSIS** [comment]
Hi @susanBuck:

I don't know if you check deprecated areas but here are a few updates:

I added a **New game?** button to the **Tic-Tac-Toe** _Project 2_ but put it under another domain to keep it kosher:

See https://ctoxfordhouse.org/p2/index.php

FYI: The system gave a warning that the **session_unset** function is being deprecated in future versions of PhP. I hard-coded the resets to **$_SESSION** to avoid this.

I'll add logic to force alternating X-O moves in the final iteration. Right now X or O can move more than once when it's their turn.

I wanted to show transition states as shown in Figure 1 on page2 of the following article:

[AI_Exchange_Tic_Tac_Toe.pdf](https://github.com/susanBuck/e2-fall20/files/5433409/AI_Exchange_Tic_Tac_Toe.pdf)

Last time I did this was in 1993 using LISP. (Unfortunately, the source code is locked up on an 8" floppy disk.)

I can do this with arrays but want to try it with the database stuff we'll be covering in the next few weeks.

Enjoying the course! Beats the LinkedIn Learning alternatives.

:-)

**Comment by susanBuck** [comment]
> I don't know if you check deprecated areas

FYI - It emails me about replies on closed posts as well, so I do. : )

Looking forward to the alternating logic (I know the first couple times I played I forgot to toggle between x and o).

Good to know about *session_unset* being on its way to deprecation. 👍
