### ISSUE TITLE
Project 2 - Production URL Issue

### ISSUE THREAD

**Issue by trnason** [susanBuck/e2-fall20#57]
Good Afternoon,

I believe I have finished project 2 and deployed it to production. However, when I go to http://e2p2.harvardtnproject.me it just says "Hello from your digital ocean server".  Any idea what I did wrong?

Git Hub URL:
https://github.com/trnason/e2/tree/master/p2

Namecheap
<img width="1154" alt="Screen Shot 2020-10-14 at 4 19 08 PM" src="https://user-images.githubusercontent.com/52473207/96046386-02eddd80-0e39-11eb-82fa-68257eb5374f.png">

**Comment by susanBuck** [comment]
It appears the Virtual Host was not set up, or was set up incorrectly. 

We can infer this because the domain (e2p2.harvardtnproject.me) is resolving to the server (meaning the DNS/domain settings are correct) - but the server is not properly handling traffic coming in via e2p2.harvardtnproject.me.

Can you share the contents of your `/etc/apache2/sites-enabled/000-default.conf` file from production so we can check your Virtual Host settings?

Also, can you confirm that after adding the Virtual Host block to this file you restarted the server (`service apache2 restart`)?

(FYI, if needed for reference, here are the notes on the Virtual Host setup procedures: https://hesweb.dev/e2/notes/production-server/production-domains#virtualhostsubdomain-setup)

**Comment by maqboolk** [comment]
Did you added virtual host? if yes, restart apache server.
Follow instructions here
https://hesweb.dev/e2/notes/production-server/summary

**Comment by trnason** [comment]
That worked! I forgot about step 5 which was to add a new VirtualHost block to the Apache config file.

Thank you for your help!
