### ISSUE TITLE
VSCode Extension - Permission Denied 

### ISSUE THREAD

**Issue by trnason** [susanBuck/e2-fall20#59]
Good Evening!

I am adding the extensions to VSCode to help with code style, but when I type in the below command in Terminal, I get a "Permission denied" message. Anyone have any ideas?

![Screen Shot 2020-10-18 at 7 16 51 PM](https://user-images.githubusercontent.com/52473207/96389674-80398b00-1176-11eb-804c-e591ca3acaf4.png)

![Screen Shot 2020-10-18 at 7 15 29 PM](https://user-images.githubusercontent.com/52473207/96389645-4bc5cf00-1176-11eb-99ef-0ff844b8254d.png)

**Comment by susanBuck** [comment]
Hi @trnason -

The command you've run is just the path to the settings file, so Terminal is trying to execute it (i.e. run it) as if it was a program. You're getting the permissions error because the file does not have executable permissions.

You need to open the file in a text editor to edit it...

In command line, you could do this with the `nano` command:

```
$ nano ~/Library/Application\ Support/Code/User/settings.json
```

Alternatively, you could open the file in some other editor (Text edit, VSCode itself, etc.).

**Comment by trnason** [comment]
I feel so dumb. Thank you!

**Comment by susanBuck** [comment]
@trnason - We've all done it, you're not alone. : )
