### ISSUE TITLE
static private methodName()

### ISSUE THREAD

**Issue by maqboolk** [susanBuck/e2-fall20#67]
@susanBuck 

Why we are allowed to create a function with **static private methodName()**?

When the function is private, the scope of that function is within the class, and We can't access it from outside, so adding **static** makes no difference. 

Don't you think, it should give us some kind of error or notice? OR there is any explanation why we would use static private?

**Comment by susanBuck** [comment]
Example use:

You have a _public static method_ that needs to access a _private property_ of the class. 

Static methods cannot access non-static properties or methods, and therefor that private property you're trying to access must also be static.

Example:

```php
<?php

class Test
{
    private static $message = 'hello';

    public static function getMessage()
    {
        # This would not work:
        # return $this->message;
        # Produces: Fatal error: Uncaught Error: Using $this when not in object context 
        
        # This would work
        return self::$message;
    }
}

$test = new Test();
var_dump($test->getMessage());
```

(Side note: Observe how static props/methods use `self::` instead of `$this` when accessed within the class.)

Here's another good example/more applicable use case: https://stackoverflow.com/a/43114908

**Comment by maqboolk** [comment]
@susanBuck 
Thank you for the example and explanation. Learning a lot about OOPs here.
