### ISSUE TITLE
Week 7 Practice Files Access

### ISSUE THREAD

**Issue by deleonl4** [susanBuck/e2-fall20#68]
I can't access week7.loc/, I tried searching by
week7.loc/index.php and still can't access.
I ran Apache and still having issues. Other files work, just not week 7. Any advice? Below is a screenshot of the index file with the structure on the left panel.

<img width="798" alt="Screen Shot 2020-10-26 at 12 03 35 PM" src="https://user-images.githubusercontent.com/47702390/97196897-5e966000-1783-11eb-884d-2db1d0514c60.png">

**Comment by susanBuck** [comment]
1. What do you see in the browser when you visit http://week7.loc?
2. Can you share a copy of your Virtual Hosts config file?

**Comment by deleonl4** [comment]
<img width="771" alt="Screen Shot 2020-10-26 at 1 42 09 PM" src="https://user-images.githubusercontent.com/47702390/97208121-29910a00-1791-11eb-8efd-d4972f99001b.png">

<img width="580" alt="Screen Shot 2020-10-26 at 1 41 54 PM" src="https://user-images.githubusercontent.com/47702390/97208079-1e3dde80-1791-11eb-9f2f-fe46609f2479.png">

**Comment by susanBuck** [comment]
That's the VirtualHosts file is from your production server.

In this case, because we're troubleshooting a local domain, we want to look at the VirtualHosts file from your computer. On your Mac, you'll find that at `/Applications/XAMPP/etc/extra/httpd-vhosts.conf`.

Also, while we're double checking things, confirm your computer's hosts file (`/private/etc/hosts`) includes the following line so that any traffic to *http://week7.loc* is mapped to your local server's IP address.

```
127.0.0.1 week7.loc
```

Finally, it never hurts to restart Apache via the XAMPP control panel, just in case this wasn't done before.

**Comment by deleonl4** [comment]
Thank you for your guidance.

I added /week7 to '/Applications/XAMPP/etc/extra/httpd-vhosts.conf' and tried to add '127.0.0.1 week7.loc' to '/private/etc/hosts' but my permission was denied.

<img width="583" alt="Screen Shot 2020-10-26 at 2 45 09 PM" src="https://user-images.githubusercontent.com/47702390/97214895-21899800-179a-11eb-995a-df497eedc8d8.png">

<img width="580" alt="Screen Shot 2020-10-26 at 2 45 50 PM" src="https://user-images.githubusercontent.com/47702390/97214906-26e6e280-179a-11eb-9b7a-51fc84f89dd3.png">

**Comment by susanBuck** [comment]
Hi @deleonl4 -

Revisit the notes/steps here as it has full instructions: https://hesweb.dev/e2/notes/local-server/local-domains

There, it explains how to edit your _hosts_ file which requires administrator privileges. 

Your VirtualHosts file looks good, just note that there you set the ServerName to `e2week7.loc`. This needs to be consistent with what you're setting in your hosts file (`week7.loc`).

**Comment by deleonl4** [comment]
Thank you! It seems this is always the step I forget one little thing on. I just re-took and paraphrased these notes.
