### ISSUE TITLE
No Access to Week 1 Assignment

### ISSUE THREAD

**Issue by deleonl4** [susanBuck/e2-fall20#7]
Hi Susan,

I emailed you yesterday with the screenshot attached. I can't access assignment 1. It says i'm not registered but I am so i'm not sure who to contact. I'm taking other classes and would like to get this assignment finishes. Is there any way you can send it to me so I have access to it while the issue resolves?

Best,
Leslie

![Screen Shot 2020-09-10 at 5 08 35 PM (2)](https://user-images.githubusercontent.com/47702390/92933294-1b22a500-f414-11ea-933f-c19d3f1ef2da.png)

**Comment by susanBuck** [comment]
Hi @deleonl4 -

It looks like you're not logged into Canvas, which is why it won't let you access the assignment. Click the icon on the top left of the screen that says login:

![image](https://user-images.githubusercontent.com/237711/92942871-05b37800-f420-11ea-96ce-56018d335197.png)

If that doesn't do the trick, let me know.

I didn't get an email from you yesterday - can you confirm you sent it to susanbuck@fas.harvard.edu?

**Comment by deleonl4** [comment]
Wow...it's always the thing that's right in your face... thank you! You would think the error message would say "You are not logged in".

**Comment by susanBuck** [comment]
I agree - I've had the same thing trip me up! The message "_only registered, enrolled users can take graded quizzes_" is misleading. 

Glad you got access now. : )
