### ISSUE TITLE
Composer.json Issue

### ISSUE THREAD

**Issue by deleonl4** [susanBuck/e2-fall20#72]
<img width="1440" alt="Screen Shot 2020-10-28 at 3 37 31 PM" src="https://user-images.githubusercontent.com/47702390/97487689-90e6bf80-1933-11eb-8cf1-af2ba632bad3.png">

I see the error on line 1 in Susan's video file as well but mines is not working with the error.

**Comment by susanBuck** [comment]
Hi @deleonl4 - Seeing if I can recreate this error on my end now. Will follow up shortly.

**Comment by susanBuck** [comment]
Try deleting the file `composer.lock` and running `composer require susanbuck/rock-paper-scissors` again.

Not sure how the composer.lock file would get a parse error because it's automatically generated, but if it has an error, we can simply remove it and then subsequent composer commands (including `composer require susanbuck/rock-paper-scissors`) will force it to be re-generated.

Let me know if that does the trick or not.

**Comment by susanBuck** [comment]
If that doesn't work, can you copy/paste the contents of your `composer.json` file here?

**Comment by deleonl4** [comment]
Thank you! That worked - I thought it wouldn't do any harm keeping the files there; got ahead of myself when I saw them at the beginnings of an earlier video.
