### ISSUE TITLE
.gitignore file not displaying on production or local server

### ISSUE THREAD

**Issue by britney-sandau** [susanBuck/e2-fall20#88]
I have a silly question. As I was doing my homework I noticed that my .gitignore folder is missing from view within my production and local terminal windows. I can view it if need be by typing the cat command. The only thing I can think of was when I was watching the videos, I did not add the .gitignore folder since it was already included in the zipfoods file structure. 

I included a screenshot if that helps.

![Screen Shot 2020-11-12 at 5 02 12 PM](https://user-images.githubusercontent.com/57762932/99002018-ce3d7680-2509-11eb-9396-0245610f3054.png)

**Comment by susanBuck** [comment]
Hi @britney-sandau - Not a stupid question at all : )

Any file starting with a period is classified as a hidden file. 

In order to see hidden files when running the `ls` (list) command, you have to add the flag `-a`(all), which configures the command to ["not ignore entries starting with ."](https://man7.org/linux/man-pages/man1/ls.1.html)

So if you amend your command from `ls -l` to `ls -la` you should see the *.gitignore* and any other hidden files.

Here's a full breakdown of the `ls -la` command: https://explainshell.com/explain?cmd=ls+-la

**Comment by britney-sandau** [comment]
Thank you so very much! This worked!
