### ISSUE TITLE
Issue When Form Submitted

### ISSUE THREAD

**Issue by pllealfunes** [susanBuck/e2-fall20#96]
Hi everyone,

I started my P3 as an animal guessing game. Where on page load a new description of an animal is displayed(random pick from associative array), then the player has to guess the animal and type their answer in an input box. On submit the player is redirected back to the game and the animal description either changes or stays the same. I noticed that the player's submitted guess is evaluated against the new animal description instead of the first description the player was guessing. Any ideas on how this could be addressed?

**Comment by susanBuck** [comment]
Hi @pllealfunes - 

Looking at the method that handles the form processing:

https://github.com/pllealfunes/e2/blob/master/p3/app/Controllers/GameController.php#L17

```php
public function playerGuess()
    {
        $this->app->validate([
            'guess' => 'required',
        ]);
        
        $guess = $this->app->input('guess');

        /*if ($guess == $randAnimal) {
            $message = "Congrats you did it";
        } else {
            $message = "Aww try again";
        }*/

        $this->app->redirect('/', [
            'guess' => $guess,
            ]);
    }
```

Is this the code that is causing the unexpected results you've described?

If so, an issue I see is that `$randAnimal` is never defined in this method.

It is defined in [AppController@index line 18](https://github.com/pllealfunes/e2/blob/master/p3/app/Controllers/AppController.php#L18) but that information is not made available to GameController@playerGuess.

A couple different ways you could "pass" this information so it is available in GameController@playerGuess:

1. Store it in a session
2. Embed it in the form as a hidden value, similar to how we [embedded the product id in the review form in ZipFoods](https://github.com/susanBuck/e2/blob/master/zipfoods/views/products/show.blade.php#L36). This way, the receiving method can retrieve that info from the form.

Of those two options, I suggest the latter, because we only need the info to persist for the single form submission.

---


ps- It'd be helpful in posts like this if you provide some context on the code you're working with. I was able to dig into your Github repo to find it, but it'd make it easier for everyone reading this if we had more details. Some tips/guidance on this here: [Forum > Getting help effectively](https://hesweb.dev/e2/forum-about#Getting%20help%20effectively)

**Comment by pllealfunes** [comment]
Yes, thank you so much...I had also thought of a session as a possibility to store the information, out of curiosity, would I have needed to use the sessionSet and sessionGet method?

**Comment by susanBuck** [comment]
@pllealfunes - Yup!

**Comment by pllealfunes** [comment]
Awesome. Thanks for the help!
