### ISSUE TITLE
e2Framework - where to put auxiliary functions

### ISSUE THREAD

**Issue by CrimsonSIS** [susanBuck/e2-fall20#97]
I have some auxiliary functions in a library that I want to use in Project 3.

In Django I try to keep Controller code separate from Python helper functions. Is there an analog file organization in the e2Framework? Where would you recommend putting them?

:-)

**Comment by susanBuck** [comment]
I suggest doing something similar to what we did in Week 10 where I pulled in an auxiliary `Products.php` class.

+ Notes: https://hesweb.dev/e2/notes/php/frameworks/overview#products-data-setup
+ Video: [Week 10 Part 3](https://www.youtube.com/embed/VYtgJrlBgB8?rel=0&showinfo=0) starting at the 23:03 mark

In this example, I put the class directly in the `app` directory, and because of our autoloading setup, it was easily accessible for use in my application.

If you wanted to organize your auxiliary files a little more, you could create a subdirectory within `app` for them, e.g. `app/Auxiliary` - you just need to make sure to include that as part of the class namespace.

So instead of:

```php
namespace App;
```

It would be:
```php
namespace App\Auxiliary;
```

And then when using/importing the class, instead of:

```php
use App\YourClassName;
```

It'd be:

```php
use App\Auxiliary\YourClassName;
```

**Comment by CrimsonSIS** [comment]
Thanks! On it...

:-)

**Comment by susanBuck** [comment]
Closing this thread but feel free to re-open if you have any questions when implementing!

**Comment by alysonann** [comment]
Is this what I should do if I need a function for my game play logic that I can access from multiple places? I'm just sticking to rock, paper, scissors, and I need my logic of who wins when my user plays (in my AppController) AND in my seed method (in AppCommand), so the fake data makes sense. I don't want to overthink it (the Products Class seems a lot more complicated than what I need?), but I don't want to repeat my code.

**Comment by susanBuck** [comment]
Hi @alysonann -

This is the pattern I'd follow for what you described. You could create a "RPS" (Rock Paper Scissors) class that had any of the shared RPS functionality.

It will seem like overkill in the small apps we're building, yes. : ) But remember, everything we're doing is really just for practice, and it will give you an opportunity to practice this design pattern and imagine how it would help you organize your code when working in a larger scale.

I like that you're thinking about repeat code and way to streamline things - that's good. 👍

**Comment by alysonann** [comment]
Okay--thank you! I figured out something that seems to work. I'm a little shaky on what I am allowed to do with outside classes and dealing with objects, but using using some prior examples I got something to function! :)

**Comment by susanBuck** [comment]
@alysonann - Took a look at your code - the RPS class and usage looks good!

A small suggestion for improvement -

I think it'd be nice if we could bundle this logic into the RPS class:

```php
$choices = ['rock','paper','scissors'];
$computerMove = $choices[rand(0, 2)];
```


Two approaches to do this:

## Approach 1
Create a [static](https://hesweb.dev/e2/notes/php/inheritance-visibility-static#static-keyword) method _getMove_ that would just return a random move (rock, paper or scissors).

Then in your controller:
```php
$computerMove = RPS::getMove();
```

## Approach 2
Embed the computer choice logic into the _playGame_ method.

If you do this, you'd want to expand on what playGame returns so you could know what the computer choice was in the controller.

So instead of just returning a result string of "win", "loss", or "tie" have it return an array of data that includes the result string _and_ the computer's move.

```php
return [
    'result' => $result,
    'computer' => $computer
];
```

Not necessary you implement either of the above - your class/solution is sufficient as is - just wanted to throw this out there "FYI".

**Comment by alysonann** [comment]
Thanks for going to look at my code! This was very helpful! :)
