### ISSUE TITLE
CSS issue

### ISSUE THREAD

**Issue by CrimsonSIS** [susanBuck/e2-fall20#98]
I changed out the HES logo on the landing page:

![image](https://user-images.githubusercontent.com/53196073/101065713-796aaa00-3563-11eb-880c-0215dfbd7099.png)

The image and text render, but the stylings aren't applying.

Here is the app.css code:

![image](https://user-images.githubusercontent.com/53196073/101066030-e67e3f80-3563-11eb-89bd-0a9c37cf44d8.png)

Added the **width** parameter, but that's not taking effect either.

Low priority but open to suggestions.

:-)

**Comment by pllealfunes** [comment]
Maybe if you try changing the name of the file? I ran into the same issue, I changed the name of the css file and changed the link tag in the master.blade.php, it worked for me.

`app.css` -> `mysteryanimal.css`

`<link href='/css/app.css' rel='stylesheet'>` -> `<link href='/css/mysteryanimal.css' rel='stylesheet'>`

**Comment by susanBuck** [comment]
Could be a cache issue, where the browser is caching a previous version of the CSS file.

Try clearing your browser cache and reloading.

A tip if you use Chrome - in your Web Inspector settings, there's an option to **Disable cache (While DevTools is open** ([screenshot](https://s3.amazonaws.com/screenshots001/2020-12-03-13-39-54.png
)). 

If you enable this and reload the page with web inspector open, it will guarantee you aren't seeing any cache'd CSS.

(This setting likely exists in other browsers as well - let me know if you don't use Chrome and need guidance on how to find it in another browser)

@pllealfunes's solution would also work because when the browser sees a new file name, it would re-fetch that file instead of loading it from cache. However, having to change the file name to refresh a cache can be cumbersome so I suggest the "Disable cache" trick.

**Comment by CrimsonSIS** [comment]
Thank you both for the rapid response. I do use Chrome. Giving it a shot!

:-)

**Comment by CrimsonSIS** [comment]
Who nu? Tenks!

![Tic_Tac_Toe_e2Framework_Version](https://user-images.githubusercontent.com/53196073/101082325-48956f80-3579-11eb-9284-aa1bfcf8359c.png)

**Comment by CrimsonSIS** [comment]
> Maybe if you try changing the name of the file? I ran into the same issue, I changed the name of the css file and changed the link tag in the master.blade.php, it worked for me.
> 
> `app.css` -> `mysteryanimal.css`
> 
> `<link href='/css/app.css' rel='stylesheet'>` -> `<link href='/css/mysteryanimal.css' rel='stylesheet'>`

Hi @pllealfunes: Just a quick follow-up. I did change the picture and it rendered the first time I refreshed. The problem was  the CSS not applying. Clearing browser data from the Chrome More Tools menu option did the trick.

Appreciate your taking the time to weigh in... :-)

**Comment by pllealfunes** [comment]
> > Maybe if you try changing the name of the file? I ran into the same issue, I changed the name of the css file and changed the link tag in the master.blade.php, it worked for me.
> > `app.css` -> `mysteryanimal.css`
> > `<link href='/css/app.css' rel='stylesheet'>` -> `<link href='/css/mysteryanimal.css' rel='stylesheet'>`
> 
> Hi @pllealfunes: Just a quick follow-up. I did change the picture and it rendered the first time I refreshed. The problem was the CSS not applying. Clearing browser data from the Chrome More Tools menu option did the trick.
> 
> Appreciate your taking the time to weigh in... :-)

Hi @CrimsonSIS, I’m glad everything worked out. I have to remember that clearing cache trick for the next time I have the same problem. Anyway, happy to help in any way that I can. Good luck on your project! 🙂
